# Generated by Django 2.2.16 on 2023-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230403_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузи изображение для поста', upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
